# Generated by Django 4.2.7 on 2025-11-26 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneKeyAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onekey_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('tier', models.CharField(choices=[('silver', 'Argent'), ('gold', 'Or'), ('platinum', 'Platine'), ('diamond', 'Diamant')], default='silver', max_length=20)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onekey_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'onekey_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneKeyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('reward_type', models.CharField(choices=[('earned', 'Gagné'), ('redeemed', 'Utilisé'), ('expired', 'Expiré'), ('bonus', 'Bonus')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onekey_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='onekey.onekeyaccount')),
            ],
            options={
                'db_table': 'onekey_rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OneKeyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earn', 'Gain'), ('redeem', 'Utilisation'), ('expire', 'Expiration'), ('adjustment', 'Ajustement')], max_length=20)),
                ('points', models.IntegerField()),
                ('booking_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('onekey_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='onekey.onekeyaccount')),
            ],
            options={
                'db_table': 'onekey_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_id'], name='onekey_tran_booking_b1fa09_idx')],
            },
        ),
    ]
