# Generated by Django 4.2.7 on 2025-11-26 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano')], db_index=True, default='fr', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['name', 'language'],
                'unique_together': {('name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('booking', 'Réservation'), ('payment', 'Paiement'), ('promotion', 'Promotion'), ('system', 'Système'), ('reminder', 'Rappel'), ('alert', 'Alerte'), ('info', 'Information')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
