# Generated by Django 4.2.7 on 2025-11-26 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'package_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Pourcentage de réduction (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='packages.packagetype')),
            ],
            options={
                'db_table': 'packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_type', models.CharField(choices=[('hotel', 'Hôtel'), ('flight', 'Vol'), ('car', 'Voiture'), ('activity', 'Activité'), ('cruise', 'Croisière')], db_index=True, max_length=20)),
                ('component_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='packages.package')),
            ],
            options={
                'db_table': 'package_components',
                'ordering': ['package', 'component_type'],
                'indexes': [models.Index(fields=['package'], name='package_com_package_018a44_idx'), models.Index(fields=['component_type', 'component_id'], name='package_com_compone_9f1f5d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status'], name='packages_status_3149ce_idx'),
        ),
    ]
