# Generated by Django 4.2.7 on 2025-11-26 20:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseCabinType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cruise_cabin_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CruiseLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cruise_lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CruiseShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('capacity', models.IntegerField(blank=True, help_text='Capacité en nombre de passagers', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('year_built', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cruise_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='cruises.cruiseline')),
            ],
            options={
                'db_table': 'cruise_ships',
                'ordering': ['cruise_line', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CruisePort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cruise_ports',
                'ordering': ['country', 'city', 'name'],
                'indexes': [models.Index(fields=['city'], name='cruise_port_city_e4ab79_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('duration_days', models.IntegerField(blank=True, help_text='Durée en jours', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_cruises', to='cruises.cruiseport')),
                ('cruise_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruises', to='cruises.cruiseline')),
                ('departure_port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_cruises', to='cruises.cruiseport')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruises', to='cruises.cruiseship')),
            ],
            options={
                'db_table': 'cruises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CruiseCabin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cabin_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('max_guests', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cabin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabins', to='cruises.cruisecabintype')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabins', to='cruises.cruise')),
            ],
            options={
                'db_table': 'cruise_cabins',
                'ordering': ['cruise', 'cabin_number'],
                'indexes': [models.Index(fields=['cruise'], name='cruise_cabi_cruise__fd60da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cruise',
            index=models.Index(fields=['cruise_line'], name='cruises_cruise__e6dec0_idx'),
        ),
        migrations.AddIndex(
            model_name='cruise',
            index=models.Index(fields=['start_date', 'end_date'], name='cruises_start_d_ba4de3_idx'),
        ),
    ]
