# Generated by Django 4.2.7 on 2025-11-26 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], db_index=True, default='medium', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='security_ev_user_id_331e99_idx'), models.Index(fields=['event_type'], name='security_ev_event_t_77edde_idx'), models.Index(fields=['severity'], name='security_ev_severit_dac121_idx'), models.Index(fields=['created_at'], name='security_ev_created_510c16_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('table_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('record_id', models.CharField(blank=True, max_length=36, null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Valeurs avant modification (format JSON)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Valeurs après modification (format JSON)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['table_name'], name='audit_logs_table_n_1d2102_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
