# Generated by Django 4.2.7 on 2025-11-26 20:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Activity Categories',
                'db_table': 'activity_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Durée en heures', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tour_activities.activitycategory')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('available_spots', models.IntegerField(blank=True, help_text='Nombre de places disponibles', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='tour_activities.activity')),
            ],
            options={
                'db_table': 'activity_schedules',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['activity'], name='activity_sc_activit_35ebf2_idx'), models.Index(fields=['start_date'], name='activity_sc_start_d_943d08_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category'], name='activities_categor_19fdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['city'], name='activities_city_fd0718_idx'),
        ),
    ]
