# Generated by Django 4.2.7 on 2025-11-26 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('seats', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('transmission', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], default='automatic', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride')], default='petrol', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'Louée'), ('maintenance', 'En maintenance')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['company', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Car Categories',
                'db_table': 'car_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarRentalCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Car Rental Companies',
                'db_table': 'car_rental_companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarRentalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(choices=[('airport', 'Aéroport'), ('city', 'Ville'), ('station', 'Gare'), ('other', 'Autre')], default='city', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='car_rentals.carrentalcompany')),
            ],
            options={
                'db_table': 'car_rental_locations',
                'ordering': ['company', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('available', models.BooleanField(default=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='car_rentals.car')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_availabilities', to='car_rentals.carrentallocation')),
            ],
            options={
                'verbose_name_plural': 'Car Availabilities',
                'db_table': 'car_availability',
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='car_rentals.carcategory'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_rentals.carrentalcompany'),
        ),
        migrations.AddIndex(
            model_name='carrentallocation',
            index=models.Index(fields=['company'], name='car_rental__company_67189f_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentallocation',
            index=models.Index(fields=['city'], name='car_rental__city_171671_idx'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['car'], name='car_availab_car_id_629faf_idx'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['location'], name='car_availab_locatio_9244a5_idx'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['start_date', 'end_date'], name='car_availab_start_d_99190e_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['company'], name='cars_company_7141b3_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='cars_categor_e637b1_idx'),
        ),
    ]
