# Generated by Django 4.2.7 on 2025-11-26 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'En attente'), ('suspended', 'Suspendu')], db_index=True, default='active', max_length=20)),
                ('check_in_time', models.TimeField(default='15:00:00')),
                ('check_out_time', models.TimeField(default='11:00:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'db_table': 'property_amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Property Categories',
                'db_table': 'property_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Room Amenities',
                'db_table': 'room_amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('max_guests', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('unavailable', 'Indisponible'), ('maintenance', 'En maintenance')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodations.property')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='accommodations.roomtype')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['property', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('image_type', models.CharField(choices=[('main', 'Principale'), ('gallery', 'Galerie'), ('room', 'Chambre'), ('amenity', 'Équipement'), ('other', 'Autre')], default='gallery', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, default='fr', max_length=10)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='accommodations.property')),
            ],
            options={
                'db_table': 'property_descriptions',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='accommodations.propertyamenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='accommodations.property')),
            ],
            options={
                'db_table': 'property_amenities_link',
            },
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'property_addresses',
                'ordering': ['country', 'city'],
                'indexes': [models.Index(fields=['city'], name='property_ad_city_c4e758_idx'), models.Index(fields=['country'], name='property_ad_country_23dd3e_idx'), models.Index(fields=['latitude', 'longitude'], name='property_ad_latitud_a71814_idx')],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accommodations.propertyaddress'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accommodations.propertycategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='accommodations.propertytype'),
        ),
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('season_type', models.CharField(choices=[('low', 'Basse saison'), ('medium', 'Moyenne saison'), ('high', 'Haute saison'), ('peak', 'Pic de saison')], default='medium', max_length=20)),
                ('start_date', models.DateField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='accommodations.room')),
            ],
            options={
                'db_table': 'room_pricing',
                'ordering': ['start_date', 'season_type'],
                'indexes': [models.Index(fields=['room'], name='room_pricin_room_id_ca2e55_idx'), models.Index(fields=['start_date', 'end_date'], name='room_pricin_start_d_9fae4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accommodations.room')),
            ],
            options={
                'verbose_name_plural': 'Room Availabilities',
                'db_table': 'room_availability',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['room'], name='room_availa_room_id_a4e8e6_idx'), models.Index(fields=['date'], name='room_availa_date_d14521_idx'), models.Index(fields=['available'], name='room_availa_availab_23d3c2_idx')],
                'unique_together': {('room', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomAmenityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_links', to='accommodations.roomamenity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='accommodations.room')),
            ],
            options={
                'db_table': 'room_amenities_link',
                'indexes': [models.Index(fields=['room'], name='room_amenit_room_id_92635c_idx')],
                'unique_together': {('room', 'amenity')},
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['property'], name='rooms_propert_67d9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='rooms_status_ee4627_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyimage',
            index=models.Index(fields=['property'], name='property_im_propert_918ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydescription',
            index=models.Index(fields=['property'], name='property_de_propert_cfce17_idx'),
        ),
        migrations.AddIndex(
            model_name='propertydescription',
            index=models.Index(fields=['language'], name='property_de_languag_ac2919_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertydescription',
            unique_together={('property', 'language')},
        ),
        migrations.AddIndex(
            model_name='propertyamenitylink',
            index=models.Index(fields=['property'], name='property_am_propert_cb7e87_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyamenitylink',
            index=models.Index(fields=['amenity'], name='property_am_amenity_e53caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenitylink',
            unique_together={('property', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties_propert_f6c75f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['address'], name='properties_address_c0c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['rating'], name='properties_rating_89c562_idx'),
        ),
    ]
