# Generated by Django 4.2.7 on 2025-11-26 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'airlines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('icao_code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'airports',
                'ordering': ['country', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_number', models.CharField(db_index=True, max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Durée du vol en minutes', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Programmé'), ('delayed', 'Retardé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], db_index=True, default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flights', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flights', to='flights.airport')),
            ],
            options={
                'db_table': 'flights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Flight Classes',
                'db_table': 'flight_classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlightAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('available_seats', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='flights.flight')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_availabilities', to='flights.flightclass')),
            ],
            options={
                'verbose_name_plural': 'Flight Availabilities',
                'db_table': 'flight_availability',
                'ordering': ['date', 'flight_class'],
            },
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['iata_code'], name='airports_iata_co_d51f22_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['city'], name='airports_city_2f0293_idx'),
        ),
        migrations.AddIndex(
            model_name='flightavailability',
            index=models.Index(fields=['flight'], name='flight_avai_flight__ecaece_idx'),
        ),
        migrations.AddIndex(
            model_name='flightavailability',
            index=models.Index(fields=['date'], name='flight_avai_date_e3f439_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flightavailability',
            unique_together={('flight', 'flight_class', 'date')},
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['airline'], name='flights_airline_f98ab3_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_airport'], name='flights_departu_f540fa_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['arrival_airport'], name='flights_arrival_9d2053_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='flights_flight__7aaa5c_idx'),
        ),
    ]
