# Generated by Django 4.2.7 on 2025-11-26 20:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_rentals', '0001_initial'),
        ('cruises', '0001_initial'),
        ('tour_activities', '0001_initial'),
        ('flights', '0001_initial'),
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('promotion_code', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('hotel', 'Hôtel'), ('flight', 'Vol'), ('car', 'Voiture'), ('activity', 'Activité'), ('cruise', 'Croisière'), ('package', 'Forfait')], db_index=True, max_length=20)),
                ('item_id', models.CharField(db_index=True, max_length=36)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_items',
                'ordering': ['booking', 'item_type'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Statuses',
                'db_table': 'booking_statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_guests',
                'ordering': ['booking', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BookingFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_date', models.DateField(db_index=True)),
                ('passengers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_details', to='bookings.bookingitem')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flights', to='flights.flight')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_flights', to='flights.flightclass')),
            ],
            options={
                'db_table': 'booking_flights',
                'ordering': ['flight_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingCruise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passengers', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cruise_details', to='bookings.bookingitem')),
                ('cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_cruises', to='cruises.cruisecabin')),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_cruises', to='cruises.cruise')),
            ],
            options={
                'db_table': 'booking_cruises',
                'ordering': ['cruise', 'cabin'],
            },
        ),
        migrations.CreateModel(
            name='BookingCar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField(db_index=True)),
                ('dropoff_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_details', to='bookings.bookingitem')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_cars', to='car_rentals.car')),
                ('dropoff_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='car_rentals.carrentallocation')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='car_rentals.carrentallocation')),
            ],
            options={
                'db_table': 'booking_cars',
                'ordering': ['pickup_date', 'dropoff_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(db_index=True)),
                ('participants', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_activities', to='tour_activities.activity')),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity_details', to='bookings.bookingitem')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_activities', to='tour_activities.activityschedule')),
            ],
            options={
                'verbose_name_plural': 'Booking Activities',
                'db_table': 'booking_activities',
                'ordering': ['activity_date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.bookingstatus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField(db_index=True)),
                ('check_out', models.DateField(db_index=True)),
                ('guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_details', to='bookings.bookingitem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='accommodations.room')),
            ],
            options={
                'db_table': 'booking_rooms',
                'ordering': ['check_in', 'check_out'],
                'indexes': [models.Index(fields=['booking_item'], name='booking_roo_booking_2f0f23_idx'), models.Index(fields=['room'], name='booking_roo_room_id_c11343_idx'), models.Index(fields=['check_in', 'check_out'], name='booking_roo_check_i_798fb0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['booking'], name='booking_ite_booking_b3bf99_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['item_type', 'item_id'], name='booking_ite_item_ty_0c4a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingguest',
            index=models.Index(fields=['booking'], name='booking_gue_booking_0eb3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingflight',
            index=models.Index(fields=['booking_item'], name='booking_fli_booking_618593_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingflight',
            index=models.Index(fields=['flight'], name='booking_fli_flight__a63560_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcruise',
            index=models.Index(fields=['booking_item'], name='booking_cru_booking_9b60dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcruise',
            index=models.Index(fields=['cruise'], name='booking_cru_cruise__3af388_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcar',
            index=models.Index(fields=['booking_item'], name='booking_car_booking_01f0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingcar',
            index=models.Index(fields=['car'], name='booking_car_car_id_9c9c16_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingactivity',
            index=models.Index(fields=['booking_item'], name='booking_act_booking_c8a0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingactivity',
            index=models.Index(fields=['activity'], name='booking_act_activit_180fec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='bookings_user_id_fdc49e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='bookings_booking_4d53ac_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status__2e3a17_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
    ]
