# Generated by Django 4.2.7 on 2025-11-26 22:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_type', models.CharField(choices=[('hotel', 'Hôtel'), ('flight', 'Vol'), ('car', 'Voiture'), ('package', 'Forfait'), ('activity', 'Activité'), ('cruise', 'Croisière')], db_index=True, max_length=20)),
                ('search_params', models.JSONField(blank=True, help_text='Paramètres de recherche au format JSON', null=True)),
                ('results_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Searches',
                'db_table': 'user_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='user_search_user_id_f62885_idx'), models.Index(fields=['search_type'], name='user_search_search__3f40fd_idx'), models.Index(fields=['created_at'], name='user_search_created_a96a8b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_data', models.JSONField(blank=True, help_text="Données de l'événement au format JSON", null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='analytics_e_user_id_f525be_idx'), models.Index(fields=['event_type'], name='analytics_e_event_t_7fd62a_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx')],
            },
        ),
    ]
